name: real_estate_env
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - graphviz
  - python-graphviz
  - streamlit            
  - pip                 
  - pip:
      - typer[all]      
      - rich             